fixing sonarqube

diff --git a/Jenkinsfile-demo b/Jenkinsfile-demo
--- a/Jenkinsfile-demo
+++ b/Jenkinsfile-demo
@@ -240,29 +240,37 @@ def nodejsSonarqube () {
 
             def OLD_SONAR_DATE
 
-              // run scan
-              sh "npm install typescript"
-              sh returnStdout: true, script: "./gradlew sonarqube -Dsonar.host.url=${SONARQUBE_URL} -Dsonar.projectKey="org.sonarqube:demo-eagle-admin" -Dsonar.projectName="org.sonarqube:demo-eagle-admin" -Dsonar.verbose=true --stacktrace --info"
+            try {
+              // get old sonar report date
+              def OLD_SONAR_DATE_JSON = sh(returnStdout: true, script: "curl -w '%{http_code}' '${SONARQUBE_STATUS_URL}'")
+              OLD_SONAR_DATE = sonarGetDate (OLD_SONAR_DATE_JSON)
+            } catch (error) {
+              firstScan = true
+            }
 
-              if ( !firstScan ) {
-                // wiat for report to be updated
-                if ( !sonarqubeReportComplete ( OLD_SONAR_DATE, SONARQUBE_STATUS_URL ) ) {
-                  echo "sonarqube report failed to complete, or timed out"
+            // run scan
+            sh "npm install typescript"
+            sh returnStdout: true, script: "./gradlew sonarqube -Dsonar.host.url=${SONARQUBE_URL} -Dsonar.projectKey="org.sonarqube:demo-eagle-admin" -Dsonar.projectName="org.sonarqube:demo-eagle-admin" -Dsonar.verbose=true --stacktrace --info"
 
-                  notifyRocketChat(
-                    "@all The latest build, ${env.BUILD_DISPLAY_NAME} of demo-eagle-admin seems to be broken. \n ${env.BUILD_URL}\n Error: \n sonarqube report failed to complete, or timed out : ${SONARQUBE_URL}",
-                    ROCKET_DEPLOY_WEBHOOK
-                  )
+            if ( !firstScan ) {
+              // wiat for report to be updated
+              if ( !sonarqubeReportComplete ( OLD_SONAR_DATE, SONARQUBE_STATUS_URL ) ) {
+                echo "sonarqube report failed to complete, or timed out"
 
-                  currentBuild.result = "FAILURE"
-                  exit 1
-                }
-              } else {
-                sleep (30)
+                notifyRocketChat(
+                  "@all The latest build, ${env.BUILD_DISPLAY_NAME} of demo-eagle-admin seems to be broken. \n ${env.BUILD_URL}\n Error: \n sonarqube report failed to complete, or timed out : ${SONARQUBE_URL}",
+                  ROCKET_DEPLOY_WEBHOOK
+                )
+
+                currentBuild.result = "FAILURE"
+                exit 1
               }
+            } else {
+              sleep (30)
+            }
 
-              // check if sonarqube passed
-              sh("oc extract secret/sonarqube-status-urls --to=${env.WORKSPACE}/sonar-runner --confirm")
+            // check if sonarqube passed
+            sh("oc extract secret/sonarqube-status-urls --to=${env.WORKSPACE}/sonar-runner --confirm")
 
             SONARQUBE_STATUS_JSON = sh(returnStdout: true, script: "curl -w '%{http_code}' '${SONARQUBE_STATUS_URL}'")
             SONARQUBE_STATUS = sonarGetStatus (SONARQUBE_STATUS_JSON)
